# Generated by Django 3.1.7 on 2021-03-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Категорія події')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активності')),
            ],
            options={
                'verbose_name': 'Категорія події',
                'verbose_name_plural': 'Категорії подій',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Підкатегорія')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус активності')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.categoryevent', verbose_name=' Категорія події')),
            ],
            options={
                'verbose_name': 'Підкатегорія події',
                'verbose_name_plural': 'Підкатегорії подій',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, default=True, max_length=128, verbose_name='Назва події')),
                ('description', models.TextField(blank=True, default=True, max_length=480, verbose_name='Опис події')),
                ('date_event', models.DateTimeField(verbose_name='Дата проведення події')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення події')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення події')),
                ('category', models.ManyToManyField(to='event.SubcategoryEvent', verbose_name='Категорії події')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Організатор')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
    ]
