# Generated by Django 3.1.7 on 2021-03-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210309_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=480, null=True, verbose_name='Опис події'),
        ),
    ]
