# Generated by Django 3.1.7 on 2021-03-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='event.categoryevent', verbose_name='Категорія події'),
        ),
    ]
