# Generated by Django 3.1.7 on 2021-03-14 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210314_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='event.categoryevent', verbose_name='Категорія події'),
        ),
    ]
