# Generated by Django 3.1.7 on 2021-03-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20210314_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format_event',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=8, verbose_name='Формат події'),
        ),
    ]
